project: "monai-3d-registration"
image_size: [64, 64, 64]

train_dataset:
  name: deepreg_synthetic
  image_size: [64, 64, 64]
  num_samples: 4000
  max_disp: 0.2
  cp_spacing: 8
  noise_std: 0.03
  smooth: true
  seed: 123

val_dataset:
  name: deepreg_synthetic
  image_size: [64, 64, 64]
  num_samples: 200
  max_disp: 0.2
  cp_spacing: 8
  noise_std: 0.03
  smooth: true
  seed: 456


model:
  name: globalnet3d
  num_channel_initial: 16
  depth: 3
  warp_mode: bilinear
  warp_padding_mode: border

loss:
  name: lncc_dvf
  kernel_size: 9
  smooth_nr: 1e-4
  smooth_dr: 1e-2
  image_weight: 1.0
  dvf_weight: 0.1


optimizer:
  name: Adam
  lr: 1e-4
  weight_decay: 1e-5

training:
  epochs: 50
  batch_size: 2
  num_workers: 4
  amp: true
  val_every: 1
  seed: 42

wandb:
  enabled: true
  project: "usregistrator"
  run_name: "deepreg_synth"
  offline: true
